# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

source 'https://github.com/CocoaPods/Specs.git'

target 'concert-camera' do
pod 'GPUImage', '~> 0.1'
end

target 'concert-cameraTests' do

end

